version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: db_aula
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:


volumes:
  db_data:
