version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_aula
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"
    networks:
      - exe04

  app:
    build: .
    container_name: nodejs-app
    ports:
      - "3001:3001"
    networks:
      - exe04

networks:
  exe04:


